version: '3.8'


services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: